### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by forCharlie** [mitmedialab/PersonalizedMultitaskLearning#1]
Hi,do you mind give me  the names or links of papers for  these methods?

**Comment by natashamjaques** [comment]
The journal paper based on this work is currently in review so we are unable to share it, but we have a shorter workshop paper that you could take a look at: http://affect.media.mit.edu/pdfs/16.Jaques-Taylor-et-al-PredictingHealthStressHappiness.pdf
